
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template


# BOTONES PRINCIPALES

btn.agregar = AGREGAR
btn.cancelar = CANCELAR
btn.modificar = MODIFICAR
btn.buscar = BUSCAR
btn.eliminar = EnombreGeneral.IngresarDato LIMINAR
btn.listar = LISTAR

# MENSAJES GENERALES

mensajeGeneral.IngreseDatos = Ingrese todos los datos:
mensajeGeneral.DatosMostrados = Datos obtenidos:
cedulaSupervisor.IngresarDato = C\u00c9DULA SUPERVISOR
cedulaGeneral.IngresarDato = CEDULA:
nombreGeneral.IngresarDato = NOMBRES:
numeroTelefonicoGeneral.IngresarDato = N\u00daMERO TELEF\u00d3NICO:
correoElectronicoGeneral.IngresarDato = CORREO ELECTR\u00d3NICO

# VENTANA PRINCIPAL 

titulo.VentanaPrincipal = SISTEMA BIBLIOTECARIO UPS

btn.RegistrarPrestamo = PRESTAMO
btn.PagarMulta = PAGAR MULTA
btn.BuscarUsuario = BUSCAR USUARIO
btn.BuscarLibro = BUSCAR LIBRO

frase.VentanPrincipal = UPS un espacio para aprender, investigar y crecer.

tituloMenu.Usuarios = Usuarios
tituloMenu.Bibliotecarios = Bibliotecarios
tituloMenu.Autores = Autores
tituloMenu.Libros = Libros
tituloMenu.Prestamos = Prestamos
tituloMenu.Sanciones = Sanciones

menuItem.BuscarUuario = Buscar Usuario
menuItem.AgregarUsuario = Agregar Usuario
menuItem.EliminarUsuario = Eliminar Usuario
menuItem.ModificarUsuario = Modificar Usuario
menuItem.ListarUsuarios = Listar Usuarios

menuItem.BuscarBibliotecario = Buscar Bibliotecario
menuItem.AgregarBibliotecario = Agregar Bibliotecario
menuItem.EliminarBibliotecario = Eliminar Bibliotecario
menuItem.ModificarBibliotecario = Modificar Bibliotecario
menuItem.ListarBibliotecarios = Listar Bibliotecarios

menuItem.BuscarAutor = Buscar Autor
menuItem.AgregarAutor = Agregar Autor
menuItem.EliminarAutor = Eliminar Autor
menuItem.ModificarAutor = Modificar Autor
menuItem.ListarAutores = Listar Autores

menuItem.BuscarLibro = Buscar Libro
menuItem.AgregarLibro = Agregar Libro
menuItem.EliminarLibro = Eliminar Libro
menuItem.ModificarLibro = Modificar Libro
menuItem.ListarLibros = Listar Libros

menuItem.BuscarPrestamo = Buscar Prestamo
menuItem.RegistrarPrestamo = Registrar Prestamo
menuItem.RegistrarDevolucion = Registrar Devolucion
menuItem.ListarPrestamos = Listar Prestamos

menuItem.BuscarSancion = Buscar Sancion
menuItem.PagarMulta = Pagar Multa
menuItem.ListarSanciones = Listar Sanciones

# VENTANA AGREGAR USUARIO

titulo.VentanaAgregarUsuario = AGREGAR USUARIO

# VENTANA BUSCAR USUARIO

titulo.VentanaBuscarUsuario = BUSCAR USUARIO

tituloTablaUsuarioBuscar.Codigo = C\u00f3digo
tituloTablaUsuarioBuscar.Fecha = Fecha
tituloTablaUsuarioBuscar.Libro = Libro
tituloTablaUsuarioBuscar.Estado = Estado

# VENTANA ELIMINAR USUARIO

titulo.VentanaEliminarUsuario = ELIMINAR USUARIO

# VENTANA MODIFICAR USUARIO 

titulo.VentanaModificarUsuario = MODIFICAR USUARIO

# VENTANA LISTAR USUARIOS

titulo.VentanaListarUsuarios= LISTAR USUARIOS










