
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template


#CEDULA DE SUPERVISOR

labelCedula_Supervisor = C\u00c9DULA SUPERVISOR
labelCedula_General = C\u00c9DULA
labelCodigo_General = C\u00d3DIGO

labelDatosUsuario = Datos de Usuario
labelDatosBibliotecario = Datos de Bibliotecario
labelDatosPrestamo = Datos de Pr\u00e9stamo
labelDatosSancion = Datos de Sanci\u00f3n
labelDatosLibro = Datos de Libro
labelDatosAutor = Datos de Autor
labelPrestamosRegistrados = Pr\u00e9stamos registrados

#TITULO DE MENUS Y OPCIONES DE MENU

tituloMenu_Usuarios = Usuarios
tituloMenu_Bibliotecarios = Bibliotecarios
tituloMenu_Autores = Autores
tituloMenu_Libros = Libros
tituloMenu_Prestamos = Pr\u00e9stamos
tituloMenu_Sanciones = Sanciones
tituloMenu_Idioma = Idioma

itemMenu_AgregarUsuario = Agregar Usuario
itemMenu_BuscarUsuario = Buscar Usuario
itemMenu_ModificarUsuario = Modificar Usuario
itemMenu_EliminarUsuario = Eliminar Usuario
itemMenu_ListarUsuarios = Listar Usuario

itemMenu_AgregarBibliotecario = Agregar Bibliotecario
itemMenu_BuscarBibliotecario = Buscar Bibliotecario
itemMenu_ModificarBibliotecario = Modificar Bibliotecario
itemMenu_EliminarBibliotecario = Eliminar Bibliotecario
itemMenu_ListarBibliotecarios = Listar Bibliotecarios

itemMenu_AgregarAutor = Agregar Autor
itemMenu_BuscarAutor = Buscar Autor
itemMenu_ModificarAutor = Modificar Autor
itemMenu_EliminarAutor = Eliminar Autor
itemMenu_ListarAutores = Listar Autores

itemMenu_AgregarLibro = Agregar Libro
itemMenu_BuscarLibro = Buscar Libro
itemMenu_ModificarLibro = Modificar Libro
itemMenu_EliminarLibro = Eliminar Libro
itemMenu_ListarLibros = Listar Libros

itemMenu_AgregarPrestamo = Agregar Pr\u00e9stamo
itemMenu_BuscarPrestamo = Buscar Pr\u00e9stamo
itemMenu_ModificarPrestamo = Modificar Pr\u00e9stamo
itemMenu_EliminarPrestamo = Eliminar Pr\u00e9stamo
itemMenu_ListarPrestamos = Listar Pr\u00e9stamos

itemMenu_BuscarSancion = Buscar Sanci\u00f3n
itemMenu_CancelarMontoSancion = Cancelar Monto de Sanci\u00f3n
itemMenu_ListarSanciones = Listar Sanciones

tituloVPrincipal = Sistema Bibliotecario
btnVPrincipal_RegistrarPrestamo = Registrar Pr\u00e9stamo
btnVPrincipal_BuscarLibro = Buscar Libro
btnVPrincipal_RegistrarDevolucion = Registrar Devoluci\u00f3n
btnVPrincipal_BuscarUsuario = Buscar Usuario

#TITULOS Y OPCIONES DE AUTORES

tituloVAgregarAutor = AGREGAR AUTOR
tituloVBuscarAutor = BUSCAR AUTOR
tituloVModificarAutor = MODIFICAR AUTOR
tituloVEliminarAutor = ELIMINAR AUTOR
tituloVListarAutores = LISTAR AUTORES

labelVAutor_Identificador = IDENTIFICADOR
labelVAutor_Nombres = NOMBRES
labelVAutor_EstiloLiterario = ESTILO LITERARIO
labelVAutor_Nacionalidad = NACIONALIDAD
labelVAutor_FechaDeNacimiento = FECHA DE NACIMIENTO

#TITULOS Y OPCIONES DE BIBLIOTECARIOS

tituloVAgregarBibliotecario = AGREGAR BIBLIOTECARIO
tituloVBuscarBibliotecario = BUSCAR BIBLIOTECARIO
tituloVModificarBibliotecario = MODIFICAR BIBLIOTECARIO
tituloVEliminarBibliotecario = ELIMINAR BIBLIOTECARIO
tituloVListarBibliotecarios = LISTAR BIBLIOTECARIO

labelVBibliotecario_Cedula = C\u00c9DULA
labelVBibliotecario_Nombres = NOMBRES
labelVBibliotecario_Telefono = N\u00daMERO TELEF\u00d3NICO
labelVBibliotecario_Correo = CORREO ELECTR\u00d3NICO
labelVBibliotecario_Sector/Area = SECTOR / \u00c1REA
labelVBibliotecario_NivelDePermiso = NIVEL DE PERMISO
labelVBibliotecario_Cargo = CARGO

RadioButtonVBibliotecario_NivelPermisoBasico = B\u00c1SICO
RadioButtonVBibliotecario_NivelPermisoAvanzado = AVANZADO

#TITULOS Y OPCIONES DE LIBROS

tituloVAgregarLibro = AGREGAR LIBRO
tituloVBuscarLibro = BUSCAR LIBRO
tituloVModificarLibro = MODIFICAR LIBRO
tituloVEliminarLibro = ELIMINAR LIBRO
tituloVListarLibros = LISTAR LIBROS

labelVLibro_ISBN = ISBN
labelVLibro_Nombre = NOMBRE
labelVLibro_CantidadTotal = CANTIDAD TOTAL
labelVLibro_GeneroLiterario = G\u00c9NERO LITERARIO
labelVLibro_FechaDePublicacion = FECHA DE PUBLICACI\u00d3N
labelVLibro_CantidadDisponible = CANTIDAD DISPONIBLE
labelVLibro_IdentificadorAutor = IDENTIFICADOR DE AUTOR
labelVLibro_NombreAutor = NOMBRE DE AUTOR

#TITULOS Y OPCIONES DE PRESTAMO

tituloVRegistrarPrestamo = REGISTRAR PR\u00c9STAMO
tituloVBuscarPRESTAMO = BUSCAR PR\u00c9STAMO
tituloVModificarPrestamo = MODIFICAR PR\u00c9STAMO
tituloVEliminarPrestamo = ELIMINAR PR\u00c9STAMO
tituloVListarPrestamos = LISTAR PR\u00c9STAMOS
tituloVRegistrarDevolucion = REGISTRAR DEVOLUCI\u00d3N

labelVPrestamo_NombreUsuario = NOMBRE DE USUARIO
labelVPrestamo_NombreLibro = NOMBRE DE LIBRO
labelVPrestamo_FechaPrestamo = FECHA DE PR\u00c9STAMO
labelVPrestamo_FechaLimite = FECHA L\u00cdMITE
labelVPrestamo_FechaDevolucion = FECHA DE DEVOLUCI\u00d3N
labelVPrestamo_Sancion = SANCI\u00d3N

labelVPrestamoTabla_Codigo = C\u00d3DIGO
labelVPrestamoTabla_CedulaUsuario = C\u00c9DULA DE USUARIO
labelVPrestamoTabla_ISBNLibro = ISBN DE LIBRO
labelVPrestamoTabla_CedulaBibliotecario = C\u00c9DULA DE BIBLIOTECARIO

# TITULOS Y OPCIONES DE SANCIONES

tituloVBuscarSancion = BUSCAR SANCI\u00d3N
tituloVCancelarMontoDeSancion = CANCELAR MONTO DE SANCI\u00d3N
tituloVListarSanciones = LISTAR SANCIONES

labelVSancion_Codigo = C\u00d3DIGO
labelVSancion_FechaSancion = FECHA DE SANCI\u00d3N
labelVSancion_Motivo = MOTIVO
labelVSancion_Monto = MONTO
labelVSancion_CodigoPrestamo = C\u00d3DIGO DE PR\u00c9STAMO
labelSancion_Pendiente = Pendiente
labelSancion_Pagada = Pagada
labelVSancion_Estado = ESTADO

LabelVSancion_MontoAPagar = MONTO A PAGAR

#TITULOS Y OPCIONES DE USUARIOS

tituloVRegistrarUsuario = REGISTRAR USUARIO
tituloVBuscarUsuario = BUSCAR USUARIO
tituloVModificarUsuario = MODIFICAR USUARIO
tituloVEliminarUsuario = ELIMINAR USUARIO
tituloVListarUsuarios = LISTAR USUARIOS

labelVUsuario_Cedula = C\u00c9DULA
labelVUsuario_Nombres = NOMBRES
labelVUsuario_Telefono = N\u00daMERO TELEF\u00d3NICO
labelVUsuario_Correo = CORREO ELECTR\u00d3NICO

# BOTONES RELACIONADOS A ACCIONES DE SISTEMA

btnAgregar = AGREGAR
btnBuscar = BUSCAR
btnListar = LISTAR
btnRegistrar = REGISTRAR
btnRegresar = REGRESAR
btnCancelar = CANCELAR
btnEliminar = ELIMINAR
btnModificar = MODIFICAR
btnCancelarMonto = CANCELAR MONTO
btnRegistrarDevolucion = REGISTRAR DEVOLUCI\u00d3N
btnLimpiarCampos = LIMPIAR CAMPOS

# MENSAJES RELACIONADO A ERRORES DE NEGOCIO

mensajeError_CodigoVacio = Error: Campo de c\u00f3digo vac\u00edo
mensajeError_CedulaVacio = Error: Campo de C\u00e9dula vac\u00edo
mensajeError_NombreVacio = Error: Campo de Nombre vac\u00edo
mensajeError_TelefonoVacio = Error: Campo de Tel\u00e9fono vac\u00edo
mensajeError_CorreoVacio = Error: Campo de Correo electr\u00f3nico vac\u00edo
mensajeError_IdentificadorVacio = Error: Campo de identificador vac\u00edo
mensajeError_EstiloLiterarioVacio = Error: Campo de estilo literario vac\u00edo
mensajeError_NacionalidadVacio = Error: Campo de nacionalidad vac\u00edo
mensajeError_FechaDeNacimientoVacio = Error: Campo de fecha de nacimiento vac\u00edo
mensajeError_CedulaSupervisorVacio = Error: Campo de c\u00e9dula de supervisor vac\u00edo

mensajeError_SectorAreaVacio = Error: Campo de Sector/\u00c1rea vac\u00edo
mensajeError_NivelDePermisoVacio = Error: Seleccione un nivel de permiso

mensajeError_ISBNVacio = Error: Campo de ISBN vac\u00edo
mensajeError_CantidadTotalVacio = Error: Campo de cantidad total vac\u00edo
mensajeError_GeneroLiterarioVacio = Error: Campo de g\u00e9nero literario vac\u00edo
mensajeError_IdentificadorAutorVacio = Error: Campo de identificador de autor vac\u00edo
mensajeError_FechaDePublicacionVacio = Error: Campo de fecha de publicaci\u00f3n vac\u00edo
mensajeError_MontoAPagarVacio = Error: Campo de monto a pagar vac\u00edo

# MENSAJES RELACIONADOS A SANCIONES Y DISPONIBILIDAD

mensajeDisponibilidad_NoHayDisponibilidad = No existe disponibilidad de libro
mensajeDevolucion_Tardia = Devoluci\u00f3n Tard\u00eda: se asign\u00f3 una sanci\u00f3n

# MENSAJES RELACIONADOS A INEXISTENCIAS

mensajeNoExiste_Libro = Error: El libro solicitado no existe
mensajeNoExiste_Usuario = Error: El usuario no existe
mensajeNoExiste_Prestamo = Error: El pr\u00e9stamo no existe
mensajeNoExiste_Sancion = Error: La sanci\u00f3n no existe
mensajeNoExiste_Bibliotecario = Error: El bibliotecario no existe
mensajeNoExiste_Autor = Error: El autor no existe

mensajeYaExiste_Usuario = Error: Ya existe un usuario con la cedula ingresada
mensajeYaExiste_Autor = Error: Ya existe un autor con el identificador ingresado
mensajeYaExiste_Prestamo = Error: Ya existe un pr\u00e9stamo con el c\u00f3digo ingresado
mensajeYaExiste_Libro = Error: Ya existe un libro con el ISBN ingresado

# MENSAJES RELACIONADOS A NIVELES DE PERMISO INSUFICIENTES

mensajePermisoInvalido = Error: El bibliotecario no cuenta con el nivel de permiso requerido
mensajeAutor_NoSePuedeEliminarExistenLibrosDeAutor = Errro: Existen libros activos relacionados al autor, eliminelos primero
mensajeLibro_NoSePuedeEliminarPrestamosActivos = Error: Existen pr\u00e9stamos activos relacionados al libro, no se puede eliminar

#MENSAJES RELACIONADOS A PROCESOS EXITOSOS

mensajeUsuario_GeneradoExitosamente = Usuario generado exitosamente
mensajeBibliotecario_GeneradoExitosamente = Bibliotecario generado exitosamente
mensajePrestamo_GeneradoExitosamente = Pr\u00e9stamo generado exitosamente
mensajeSancion_PagadaExitosamente = Sanci\u00f3n pagada exitosamente
mensajeLibro_GeneradoExitosamente = Libro generado exitosamente
mensajeLibro_EncontradoExitosamente = Libro encontrado exitosamente
mensajeAutor_GeneradoExitosamente = Autor generado exitosamente

mensajeAutor_EliminadoExitosamente = Autor eliminado exitosamente
mensajeBibliotecario_EliminadoExitosamente = Bibliotecario eliminado exitosamente
mensajeUsuario_EliminadoExitosamente = Usuario eliminado exitosamente
mensajePrestamo_EliminadoExitosamente = Pr\u00e9stamo eliminado exitosamente
mensajeLibro_EliminadoExitosamente = Libro eliminado exitosamente

mensajeAutor_ModificadoExitosamente = Autor modificado exitosamente
mensajeBibliotecario_ModificadoExitosamente = Bibliotecario modificado exitosamente
mensajeUsuario_ModificadoExitosamente = Usuario modificado exitosamente
mensajePrestamo_ModificadoExitosamente = Pr\u00e9stamo modificado exitosamente
mensajeLibro_ModificadoExitosamente = Libro modificado exitosamente

mensajePrestamo_DevolucionExitosa = Devoluci\u00f3n registrada exitosamente

# MENSAJES RELACIONADOS A ERRORES DE FORMATO NUMERO ---> STRING

mensajeError_NumberFormat = Ingrese un valor numerico v\u00e1lido

#MENSAJE RELACIONA A SANCIONES GENERADAS POR DEVOLUCIONES EN DIAS TARDIOS

mensajeDevolucionTardia = Devoluci\u00f3n Tard\u00eda: se asigno una multa de 10 d\u00f3lares
motivoMultaSancion_Taria = Devoluci\u00f3n tard\u00eda
mensajeError_PagoInsuficiente = Error: El monto ingresado es insuficiente para cubrir la sanci\u00f3n

mensajeError_PrimeroBuscarUsuario = Busque un usuario para modificar
mensajeError_PrimeroBuscarPrestamo = Busque un pr\u00e9stamo primero
mensajeError_PrimeroBuscarBibliotecario = Busque un bibliotecario primero
mensajeError_PrimeroBuscarAutor = Busque un autor primero
mensajeError_PrimeroBuscarLibro = Busque un libro primero
mensajeError_PrimeroBuscarSancion = Busque una sanci\u00f3n primero